export const SHOW_CREATE_COMMENT = 'SHOW_CREATE_COMMENT';
export const SHOW_MODAL = 'SHOW_MODAL';
export const LOADING_MESSAGE = 'LOADING_MESSAGE';
export const SET_PAGE_INITIAL_STATE = 'SET_PAGE_INITIAL_STATE';
export const SET_PAGE_DATA_SHOW_POST = 'SET_PAGE_DATA_SHOW_POST';
export const SET_PAGE_DATA_SHOW_SETTINGS = 'SET_PAGE_DATA_SHOW_SETTINGD';
export const SET_PAGE_DATA_POST_MARKER_ID = 'SET_PAGE_DATA_POST_MARKER_ID';
export const SET_PAGE_DATA_FORUM_MARKER_ID = 'SET_PAGE_DATA_FORUM_MARKER_ID';
export const SET_SIGN_UP_DATA = 'SET_SIGN_UP_DATA';
export const RESET_SIGN_UP_DATA = 'RESET_SIGN_UP_DATA';
export const SET_LOGIN_DATA = 'SET_LOGIN_DATA';
export const RESET_LOGIN_DATA = 'RESET_LOGIN_DATA';
export const SET_RESET_PASSWORD = 'SET_RESET_PASSWORD';
export const SET_MENU_BAR = 'SET_MENU_BAR';
export const SET_CREATE_MENU = 'SET_CREATE_MENU';

export const INITIALISE_POST_EDIT_INFO = 'INITIALISE_POST_EDIT_INFO';
export const INITIALISE_USER_EDIT_INFO = 'INITIALISE_USER_EDIT_INFO';
export const SET_SHOW_POST_FORM = 'SET_SHOW_POST_FORM'
export const EDIT_USER_INFO = 'EDIT_USER_INFO';
export const EDIT_POST_INFO = 'EDIT_POST_INFO';
export const RESET_POST_INFO = 'RESET_POST_INFO';
export const RESET_HOME_PAGE_DATA = 'RESET_HOME_PAGE_DATA';
export const RESET_PROFILE_PAGE_DATA = 'RESET_PROFILE_PAGE_DATA';
export const RESET_USER_PAGE_DATA = 'RESET_USER_PAGE_DATA';
export const RESET_GLOBALS = 'RESET_GLOBALS';
export const SET_SHOW_SCROLL_UP_BUTTON = 'SET_SHOW_SCROLL_UP_BUTTON';

