export const SHOW_CREATE_COMMENT = 'SHOW_CREATE_COMMENT';
export const SHOW_MODAL = 'SHOW_MODAL';
export const POST_DETAILS = 'POST_DETAILS';
export const LOADING_MESSAGE = 'LOADING_MESSAGE';
export const POSTS_USER_TYPE = 'POSTS_USER_TYPE';
export const FORUMS_USER_TYPE = 'FORUMS_USER_TYPE';