export const GET_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_POSTS_ERROR = "GET_ALL_POSTS_ERRORS";

export const GET_SINGLE_POST_REQUEST = "GET_SINGLE_POST_REQUEST";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
export const GET_SINGLE_POST_ERROR = "GET_SINGLE_POST_ERROR";

export const ADD_NEW_POST_REQUEST = "ADD_NEW_POST_REQUEST";
export const ADD_NEW_POST_SUCCESS = "ADD_NEW_POST_SUCCESS";
export const ADD_NEW_POST_ERROR = "ADD_NEW_POST_ERROR";

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";

export const LIKE_COMMENT_REQUEST = "LIKE_COMMENT_REQUEST";
export const LIKE_COMMENT_SUCCESS = "LIKE_COMMENT_SUCCESS";
export const LIKE_COMMENT_ERROR = "LIKE_COMMENT_ERROR";

export const EDIT_COMMENT_REQUEST = "EDIT_COMMENT_REQUEST";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_ERROR = "EDIT_COMMENT_ERROR";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";

export const ADD_REPLY_REQUEST = "ADD_REPLY_REQUEST";
export const ADD_REPLY_SUCCESS = "ADD_REPLY_SUCCESS";
export const ADD_REPLY_ERROR = "ADD_REPLY_ERROR";

export const LIKE_REPLY_REQUEST = "LIKE_REPLY_REQUEST";
export const LIKE_REPLY_SUCCESS = "LIKE_REPLY_SUCCESS";
export const LIKE_REPLY_ERROR = "LIKE_REPLY_ERROR";

export const EDIT_REPLY_REQUEST = "EDIT_REPLY_REQUEST";
export const EDIT_REPLY_SUCCESS = "EDIT_REPLY_SUCCESS";
export const EDIT_REPLY_ERROR = "EDIT_REPLY_ERROR";

export const DELETE_REPLY_REQUEST = "DELETE_REPLY_REQUEST";
export const DELETE_REPLY_SUCCESS = "DELETE_REPLY_SUCCESS";
export const DELETE_REPLY_ERROR = "DELETE_REPLY_ERROR";

export const NEW_POST_RESET = "NEW_POST_RESET";
export const CLEAR_POST_ERRORS = "CLEAR_POST_ERRORS";

export const SINGLE_POST_RESET = "SINGLE_POST_RESET"
